.. _cmdline-interface-label:

------------------------------------
Python module interface: ``ideal_module.py``
------------------------------------

IDEAL has been written in a modular way, such that its functionality is available to research users via python modules. 
The ``bin/ideal_module.py`` exposes most of the IDEAL main functionalities and allows the user to easily start simulations via python scripting and retrieve info on the dicom data.
A user example can be found in ``bin/main_ct.py``.
